/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EducationRole;

import Business.WorkQueue.EducationVolunteerWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author vidhi
 */
public class ViewRequestDetailsJPanel extends javax.swing.JPanel {
    
     private JPanel userProcessContainer;
     private EducationVolunteerWorkRequest request;

    /**
     * Creates new form ViewRequestDetailsJPanel
     */
    public ViewRequestDetailsJPanel(JPanel userProcessContainer, EducationVolunteerWorkRequest request ) {
        
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        initComponents();
        populateRequestTable();
    }
    
    private void populateRequestTable(){
        
            jobTitleJTextField.setText(request.getJobTitle());
            volunteeringDate.setDate(request.getDate());

            Date time = null;
            String volTime = request.getTime();
            SimpleDateFormat formatterDefault = new SimpleDateFormat("HH:mm");

            try {
                time = formatterDefault.parse(volTime);
            } catch (ParseException ex) {

            }

            volunteeringTime.setValue(time);

            numberOfVolunteersJTextField.setText(String.valueOf(request.getNumberOfVolunteers()));
            numberOfHoursJTextField.setText(String.valueOf(request.getNumberOfhours()));
            requirementsJTextArea.setText(request.getMessage());
            placeJTextField.setText(request.getPlace());
            areaJTextField.setText(request.getArea());
            numberOfStudentsJTextField.setText(String.valueOf(request.getNumberOfStudents()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jobTitleJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        volunteeringDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        volunteeringTime = new javax.swing.JSpinner(sm);
        placeJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberOfVolunteersJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numberOfStudentsJTextField = new javax.swing.JTextField();
        numberOfHoursJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requirementsJTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        areaJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(180, 195, 195));

        btnBack.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Job Title:");

        jobTitleJTextField.setEditable(false);
        jobTitleJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel3.setText("Date:");

        volunteeringDate.setEnabled(false);
        volunteeringDate.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel7.setText("Time: ");

        JSpinner.DateEditor de = new JSpinner.DateEditor(volunteeringTime, "HH:mm");
        volunteeringTime.setEditor(de);
        volunteeringTime.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        volunteeringTime.setEnabled(false);

        placeJTextField.setEditable(false);
        placeJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Place:");

        jLabel4.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Number of Hours:");

        numberOfVolunteersJTextField.setEditable(false);
        numberOfVolunteersJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Number of Students:");

        numberOfStudentsJTextField.setEditable(false);
        numberOfStudentsJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        numberOfStudentsJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfStudentsJTextFieldActionPerformed(evt);
            }
        });

        numberOfHoursJTextField.setEditable(false);
        numberOfHoursJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        numberOfHoursJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfHoursJTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Requirements:");

        jLabel5.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Number of Volunteers:");

        btnUpdate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        requirementsJTextArea.setEditable(false);
        requirementsJTextArea.setColumns(20);
        requirementsJTextArea.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        requirementsJTextArea.setRows(5);
        jScrollPane1.setViewportView(requirementsJTextArea);

        jLabel10.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Education Department Work Area");

        jLabel11.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Area:");

        areaJTextField.setEditable(false);
        areaJTextField.setFont(new java.awt.Font(".SF NS Mono", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfHoursJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(volunteeringTime, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(placeJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jobTitleJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numberOfVolunteersJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(volunteeringDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numberOfStudentsJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(15, 15, 15)
                                .addComponent(btnSave))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(areaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jobTitleJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volunteeringDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volunteeringTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfVolunteersJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(numberOfStudentsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfHoursJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EducationDepartmentWorkAreaJPanel dwjp = (EducationDepartmentWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        jobTitleJTextField.setEditable(true);
        placeJTextField.setEditable(true);
        numberOfVolunteersJTextField.setEditable(true);
        numberOfStudentsJTextField.setEditable(true);
        numberOfHoursJTextField.setEditable(true);
        requirementsJTextArea.setEditable(true);
        volunteeringDate.setEnabled(true);
        volunteeringTime.setEnabled(true);
        areaJTextField.setEditable(true);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        
        String jobTitle = jobTitleJTextField.getText();
        if(jobTitle == null || jobTitle.equals("")){ 
            JOptionPane.showMessageDialog(null, "Job Title can't be empty!");
            return;
        }
        request.setJobTitle(jobTitle);
        
        Date volDate = volunteeringDate.getDate();
        if(volDate == null || volDate.equals("")){ 
            JOptionPane.showMessageDialog(null, "Date can't be empty!");
            return;
        }
        if(volDate.before(new Date())){
            JOptionPane.showMessageDialog(null, "Date and Time can't be in past.");
            return;
        }
        request.setDate(volDate);
        
        SimpleDateFormat format = new SimpleDateFormat("HH:mm");      
        Date time =  (Date) volunteeringTime.getValue();
        String volTime = format.format(time);
        if(volTime == null || volTime.equals("")){ 
            JOptionPane.showMessageDialog(null, "Time can't be empty!");
            return;
        }
        request.setTime(volTime);
        
        String place = placeJTextField.getText();
        if(place == null || place.equals("")){ 
            JOptionPane.showMessageDialog(null, "Place can't be empty!");
            return;
        }
        request.setPlace(place);
        
        String area = areaJTextField.getText();
        if(area == null || area.equals("")){ 
            JOptionPane.showMessageDialog(null, "Area can't be empty!");
            return;
        }
        request.setArea(area);
            
            
        String hour = numberOfHoursJTextField.getText();
        if(hour == null || hour.equals("")){ 
            JOptionPane.showMessageDialog(null, "Number of Hours can't be empty!");
            return;
        }
         try {
            Integer.parseInt(hour);    
        } catch (NumberFormatException e){    
            JOptionPane.showMessageDialog(null, "Please enter a number for Number Of Hours.");
            return;
        }
        Integer numbofHours = Integer.parseInt(hour);
        if(numbofHours<=0)
        {
            JOptionPane.showMessageDialog(null, "Number of hours should be greater than 0.");
            return;
        }
        request.setNumberOfhours(numbofHours);
        
       String student = numberOfStudentsJTextField.getText();
        if(student == null || student.equals("")){ 
            JOptionPane.showMessageDialog(null, "Number of Students can't be empty!");
            return;
        } 
        try {
            Integer.parseInt(student);    
        } catch (NumberFormatException e){    
            JOptionPane.showMessageDialog(null, "Please enter a number for Number Of Students.");
            return;
        }
        Integer numbOfStudents = Integer.parseInt(student);
        if(numbOfStudents<=0)
        {
            JOptionPane.showMessageDialog(null, "Number of students should be greater than 0.");
            return;
        }
        request.setNumberOfStudents(numbOfStudents);
            
        String vol = numberOfVolunteersJTextField.getText();
        if(vol == null || vol.equals("")){ 
            JOptionPane.showMessageDialog(null, "Number of Volunteers can't be empty!");
            return;
        }  
        try {
            Integer.parseInt(vol);
        } catch (NumberFormatException e){  
            JOptionPane.showMessageDialog(null, "Please enter a number for Number Of Volunteers.");
            return;
        }
        Integer numbOfVol = Integer.parseInt(vol);
        if(numbOfVol<=0)
        {
            JOptionPane.showMessageDialog(null, "Number of volunteers should be greater than 0.");
            return;
        }
        int currentVol = request.getNumberOfVolunteers();
        int currentVac = request.getCurrentVacancy();
        
        int assigned = currentVol - currentVac;
        if(numbOfVol < assigned){
            JOptionPane.showMessageDialog(null, "Number of Volunteers should be greater than already assigned volunteers!");
            return; 
        }
        request.setNumberOfVolunteers(numbOfVol);
        request.setCurrentVacancy(request.getNumberOfVolunteers()-currentVol+currentVac);
        
        
        String message = requirementsJTextArea.getText();
        if(message == null || message.equals("")){ 
            JOptionPane.showMessageDialog(null, "Requirements can't be empty!");
            return;
        }
        request.setMessage(message);
            
           
        if(request.getCurrentVacancy() == 0){
            request.setStatus("Completed");
        } else if(request.getCurrentVacancy() == request.getNumberOfVolunteers()){
            request.setStatus("Sent");
        } else {
           request.setStatus("Pending");
        }
            
        
        JOptionPane.showMessageDialog(null, "Request Details Updated Successfully");
        
        jobTitleJTextField.setEditable(false);
        placeJTextField.setEditable(false);
        numberOfVolunteersJTextField.setEditable(false);
        numberOfStudentsJTextField.setEditable(false);
        numberOfHoursJTextField.setEditable(false);
        requirementsJTextArea.setEditable(false);
        volunteeringDate.setEnabled(false);
        volunteeringTime.setEnabled(false);
        areaJTextField.setEditable(false);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void numberOfHoursJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfHoursJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfHoursJTextFieldActionPerformed

    private void numberOfStudentsJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfStudentsJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfStudentsJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaJTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jobTitleJTextField;
    private javax.swing.JTextField numberOfHoursJTextField;
    private javax.swing.JTextField numberOfStudentsJTextField;
    private javax.swing.JTextField numberOfVolunteersJTextField;
    private javax.swing.JTextField placeJTextField;
    private javax.swing.JTextArea requirementsJTextArea;
    private com.toedter.calendar.JDateChooser volunteeringDate;
    private javax.swing.JSpinner volunteeringTime;
    // End of variables declaration//GEN-END:variables
}
